### ISSUE TITLE
still getting error of "error getting token" after update to .04

### ISSUE THREAD

**Issue by Bash141s** [rickeylohia/plugin.video.stalkervod#12]
still getting error of "error getting token" after update to .04

**Comment by rickeylohia** [comment]
Can enable debug logs in kodi and provide logs

**Comment by vporet** [comment]
> still getting error of "error getting token" after update to .04

Same for me..

**Comment by Bash141s** [comment]
> Can you enable debug logs in kodi and provide logs
2024-01-26 20:06:14.108 T:3136  warning <general>: plugin.video.stalkervod: We could not use the cache since it is invalid or non-existent.
2024-01-26 20:06:14.756 T:3136    error <general>: plugin.video.stalkervod: Error getting token, statusCode=404
2024-01-26 20:06:16.344 T:8884  warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-01-26 20:06:16.412 T:3136     info <general>: Skipped 3 duplicate messages..
2024-01-26 20:06:16.412 T:3136    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\addon_entry.py", line 7, in <module>
                                                       run(argv)
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 280, in run
                                                       stalker_addon.router(argv[2][1:])
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 273, in router
                                                       self.__list_vod_categories()
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 67, in __list_vod_categories
                                                       categories = Api.get_vod_categories()
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\api.py", line 46, in get_vod_categories
                                                       return Api.__call_stalker_portal(params)['js']
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\api.py", line 26, in __call_stalker_portal
                                                       token = auth.get_token(retries > 0)
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\auth.py", line 51, in get_token
                                                       raise Exception
                                                   Exception
                                                   -->End of Python script error report<--
                                                   
2024-01-26 20:06:16.429 T:1464     info <general>: CActiveAESink::OpenSink - initialize sink
2024-01-26 20:06:16.438 T:8328    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.stalkervod/
2024-01-26 20:06:16.444 T:8884    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.stalkervod/) failed

**Comment by Bash141s** [comment]
> Can you enable debug logs in kodi and provide logs

2024-01-26 20:06:14.108 T:3136  warning <general>: plugin.video.stalkervod: We could not use the cache since it is invalid or non-existent.
2024-01-26 20:06:14.756 T:3136    error <general>: plugin.video.stalkervod: Error getting token, statusCode=404
2024-01-26 20:06:16.344 T:8884  warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-01-26 20:06:16.412 T:3136     info <general>: Skipped 3 duplicate messages..
2024-01-26 20:06:16.412 T:3136    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\addon_entry.py", line 7, in <module>
                                                       run(argv)
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 280, in run
                                                       stalker_addon.router(argv[2][1:])
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 273, in router
                                                       self.__list_vod_categories()
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 67, in __list_vod_categories
                                                       categories = Api.get_vod_categories()
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\api.py", line 46, in get_vod_categories
                                                       return Api.__call_stalker_portal(params)['js']
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\api.py", line 26, in __call_stalker_portal
                                                       token = auth.get_token(retries > 0)
                                                     File "C:\Users\Ahmad\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\auth.py", line 51, in get_token
                                                       raise Exception
                                                   Exception
                                                   -->End of Python script error report<--
                                                   
2024-01-26 20:06:16.429 T:1464     info <general>: CActiveAESink::OpenSink - initialize sink
2024-01-26 20:06:16.438 T:8328    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.stalkervod/
2024-01-26 20:06:16.444 T:8884    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.stalkervod/) failed

**Comment by rickeylohia** [comment]
> > still getting error of "error getting token" after update to .04
> 
> Same for me..
> 
> logs:
> 
> 2024-01-26 11:48:20.510 T:56613 error : plugin.video.stalkervod: Error getting token, statusCode=404 2024-01-26 11:48:20.510 T:56613 debug : plugin.video.stalkervod: Token Response <title>404 Not Found</title>
> # 404 Not Found
> 
> openresty
> 
> 2024-01-26 11:48:20.519 T:50240 debug : ------ Window Init (DialogConfirm.xml) ------ 2024-01-26 11:48:23.087 T:50240 debug : ProcessMouse: trying mouse action leftclick 2024-01-26 11:48:23.324 T:50240 debug : ------ Window Deinit (DialogConfirm.xml) ------ 2024-01-26 11:48:23.333 T:56613 error : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'Exception'> Traceback (most recent call last): File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/addon_entry.py", line 7, in run(argv) File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 280, in run stalker_addon.router(argv[2][1:]) File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 273, in router self.__list_vod_categories() File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 67, in __list_vod_categories categories = Api.get_vod_categories() ^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/api.py", line 46, in get_vod_categories return Api.__call_stalker_portal(params)['js'] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/api.py", line 26, in __call_stalker_portal token = auth.get_token(retries > 0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/auth.py", line 51, in get_token raise Exception Exception -->End of Python script error report<--
> 
> The problem is that the script try to open http://_URL server_**/stalker_portal/server/load.php** but this file doesn't exist !

What's the URL of your IPTV portal?

**Comment by Bash141s** [comment]
> > > still getting error of "error getting token" after update to .04
> > 
> > 
> > Same for me..
> > logs:
> > 2024-01-26 11:48:20.510 T:56613 error : plugin.video.stalkervod: Error getting token, statusCode=404 2024-01-26 11:48:20.510 T:56613 debug : plugin.video.stalkervod: Token Response <title>404 Not Found</title>
> > # 404 Not Found
> > openresty
> > 2024-01-26 11:48:20.519 T:50240 debug : ------ Window Init (DialogConfirm.xml) ------ 2024-01-26 11:48:23.087 T:50240 debug : ProcessMouse: trying mouse action leftclick 2024-01-26 11:48:23.324 T:50240 debug : ------ Window Deinit (DialogConfirm.xml) ------ 2024-01-26 11:48:23.333 T:56613 error : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'Exception'> Traceback (most recent call last): File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/addon_entry.py", line 7, in run(argv) File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 280, in run stalker_addon.router(argv[2][1:]) File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 273, in router self.__list_vod_categories() File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 67, in __list_vod_categories categories = Api.get_vod_categories() ^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/api.py", line 46, in get_vod_categories return Api.__call_stalker_portal(params)['js'] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/api.py", line 26, in __call_stalker_portal token = auth.get_token(retries > 0) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/auth.py", line 51, in get_token raise Exception Exception -->End of Python script error report<--
> > The problem is that the script try to open http://_URL server_**/stalker_portal/server/load.php** but this file doesn't exist !
> 
> What's the URL of your IPTV portal?

http://001004.eu:8080/c/
00:1a:79:ad:78:c0
EXPIRE ➤ January 28, 2024, 2:06 pm

**Comment by rickeylohia** [comment]
I see

**Comment by rickeylohia** [comment]
I see the issue seems the portal you are using has a diff path, will push a change

**Comment by albilia** [comment]
Same thing here - error token.
I manage to connect with the server address and mac address in other apps that I have on my iPhone and Apple TV.
Server address: http://mol-2.com:8080/c/
MAC address: 00:1A:79:ca:ea:3c

I uploaded to pastebin the summary of the error message and not the entire log file.
Hope it's ok.
PasteBin Link: https://pastebin.com/Kee3WDgv

Thanks in advance : )

**Comment by egImmortal** [comment]
Hi, I'm also facing the same issue also i notice that any server address that has a port number in it causes the issue.
Thanks in advance for your response!!

**Comment by untiiis** [comment]
Hello,
I have exactly the same problem, in fact I've always had this problem, I've never been able to connect to a mac address.

**Comment by rickeylohia** [comment]
this should be resolved with v0.0.5

**Comment by untiiis** [comment]
Thank you for updating
I tested and indeed, I don't get theerror message 
On the other hand, the addon only displays the movies folder and not the tv show/series

and another problem, when I try to access the movie folder, an error message is displayed

(my iptv server works on other apps)

**Comment by rickeylohia** [comment]
@untiiis 
Can you enable debug logs in kodi and provide the the log file?

**Comment by untiiis** [comment]
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ValueError'>
Error Contents: invalid literal for int() with base 10: 'N/A'
Traceback (most recent call last):
    File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\addon_entry.py", line 7, in <module>
        run(argv)
    File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 280, in run
        stalker_addon.router(argv[2][1:])
    File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 251, in router
       self.__list_videos(params)
    File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 111, in __list_videos
        StalkerAddon.__create_video_listing(videos, params)
    File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.stalkervod\lib\addon.py", line 152, in __create_video_listing
        video_info.setDuration(int(video['time']) * 60)
ValueError: invalid literal for int() with base 10: 'N/A'
 -->End of Python script error report<--
                                                   
error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.stalkervod/?action=listing&category=SD%7c%20BOX%20OFFICE&category_id=121&fav=0&page=1&search_term&update_listing=False

error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.stalkervod/?action=listing&category=SD%7c%20BOX%20OFFICE&category_id=121&fav=0&page=1&search_term&update_listing=False) failed

**Comment by untiiis** [comment]
@rickeylohia

**Comment by rickeylohia** [comment]
@untiiis can you try with the new version v0.0.6

**Comment by rickeylohia** [comment]
issues should be fixed with v1.0.0 and be available in official kodi repo soon
