### ISSUE TITLE
Add-on Error, both libreelec or macOS Kodi 20.1 or 20.3

### ISSUE THREAD

**Issue by vporet** [rickeylohia/plugin.video.stalkervod#9]
Hi,

I try to use your add-on but both Libreelec or macOs return error (Kodi 20.1 and 20.3).
On the log file I've got this : 

2024-01-17 15:06:30.507 T:3184494   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/models.py", line 971, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Volumes/Kodi 2/Kodi.app/Contents/Libraries/lib/python3.11/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Volumes/Kodi 2/Kodi.app/Contents/Libraries/lib/python3.11/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Volumes/Kodi 2/Kodi.app/Contents/Libraries/lib/python3.11/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/addon_entry.py", line 7, in <module>
                                                       run(argv)
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 279, in run
                                                       router(argv[2][1:])
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 273, in router
                                                       list_categories()
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/addon.py", line 52, in list_categories
                                                       categories = get_categories()
                                                                    ^^^^^^^^^^^^^^^^
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/api.py", line 38, in get_categories
                                                       return __call_stalker_portal(params)['js']
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/api.py", line 19, in __call_stalker_portal
                                                       token = _auth.get_token(retries > 0)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/plugin.video.stalkervod/lib/auth.py", line 83, in get_token
                                                       ).json()['js']['token']
                                                         ^^^^^^
                                                     File "/Users/vincentporet/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/models.py", line 975, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

**Comment by rickeylohia** [comment]
not sure whats causing the error most likely the portal config is incorrect.
have added some debug logs in v0.0.4, can you try addon v0.0.4 with debug enabled and provide the logs.

note: v0.0.4 is not available in the official repo yet (can take few days) or install manually from below
https://github.com/rickeylohia/plugin.video.stalkervod/releases/tag/v0.0.4

**Comment by rickeylohia** [comment]
please re-open if you still have the issue and provide debug logs if possible
